# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for CivilQntify.

Build with:  pyinstaller civilqntify.spec
"""

import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# ── Paths ────────────────────────────────────────────────────────────
ROOT = os.path.abspath(SPECPATH)

# Application icon — generated by scripts/make_icon.py from
# app/resources/icon.png. Embedded into the Windows .exe by PyInstaller;
# safely ignored (warning only) when building on Linux/macOS.
ICON = os.path.join(ROOT, "app", "resources", "icon.ico")

# Ensure local packages are importable when collecting submodules.
# collect_submodules() searches sys.path, so ROOT must be present
# before the call — otherwise it returns an empty list and hiddenimports
# silently misses local modules (e.g. app.pricing, app.widgets.*).
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

# ── datas: bundle resource files & library data alongside the app ───
datas = (
    [
        (os.path.join(ROOT, "app", "resources"), os.path.join("app", "resources")),
    ]
    + collect_data_files("matplotlib", includes=["*.json", "*.png", "*.svg", "*.ttf"])
)

# ── hiddenimports: dynamically collect all local & library submodules
# Use collect_submodules for bulk discovery plus an explicit fallback list.
# The explicit list guarantees coverage when collect_submodules misses
# modules that are only imported conditionally or inside functions, and
# protects against a future regression if sys.path handling changes.
_hidden_collected = []
for _pkg in ("app", "concrete_mix", "material_quantify", "history"):
    try:
        _hidden_collected += collect_submodules(_pkg)
    except Exception:
        pass
try:
    _hidden_collected += collect_submodules("PyQt6")
except Exception:
    pass

hiddenimports = _hidden_collected + [
    # Explicit fallbacks — mirrors the pre-dynamic explicit list and
    # covers modules that are imported lazily or via Qt plugins.
    "app",
    "app.main",
    "app.styles",
    "app.unit_preferences",
    "app.widgets",
    "app.widgets.concrete_tab",
    "app.widgets.material_quantify_tab",
    "app.widgets.cost_estimation_tab",
    "app.widgets.history_tab",
    "app.widgets.history_detail_dialog",
    "app.widgets.report_preview_dialog",
    "app.widgets.settings_dialog",
    "app.widgets.info_button",
    "app.widgets.result_panel",
    "app.widgets.quant_result_panel",
    "app.widgets.cost_result_panel",
    "app.widgets.psd_widget",
    "app.widgets.weather_widget",
    "app.workers",
    "app.workers.mix_design_worker",
    "app.workers.quantification_worker",
    "app.pricing",
    "app.pricing.price_sheet_service",
    "app.pricing.price_sheet_worker",
    "app.weather",
    "app.weather.ghana_cities",
    "app.weather.weather_service",
    "app.weather.weather_worker",
    "app.weather.weatherapi_service",
    "concrete_mix",
    "concrete_mix.codes",
    "concrete_mix.codes.aci211",
    "concrete_mix.codes.is10262",
    "concrete_mix.codes.doe",
    "concrete_mix.codes.base",
    "concrete_mix.codes.tables",
    "concrete_mix.codes.tables.aci_tables",
    "concrete_mix.codes.tables.is_tables",
    "concrete_mix.codes.tables.doe_tables",
    "concrete_mix.codes.tables.grading_bands",
    "concrete_mix.engine",
    "concrete_mix.engine.grading",
    "concrete_mix.engine.moisture_correction",
    "concrete_mix.engine.proportioner",
    "concrete_mix.engine.psd",
    "concrete_mix.engine.volume_calculator",
    "concrete_mix.estimators",
    "concrete_mix.estimators.carbon",
    "concrete_mix.estimators.cost",
    "concrete_mix.estimators.strength_from_ratio",
    "concrete_mix.export",
    "concrete_mix.export.csv_export",
    "concrete_mix.export.json_export",
    "concrete_mix.export.pdf_report",
    "concrete_mix.export.text_report",
    "concrete_mix.models",
    "concrete_mix.models.materials",
    "concrete_mix.models.mix_input",
    "concrete_mix.models.mix_result",
    "concrete_mix.utils",
    "concrete_mix.utils.constants",
    "concrete_mix.utils.units",
    "concrete_mix.validation",
    "concrete_mix.validation.validators",
    "material_quantify",
    "material_quantify.engine",
    "material_quantify.engine.quantifier",
    "material_quantify.models",
    "material_quantify.models.bill",
    "material_quantify.models.elements",
    "material_quantify.models.transfer_data",
    "history",
    "history.db",
    "history.serializers",
    "matplotlib",
    "matplotlib.backends.backend_qtagg",
    "matplotlib.backends.backend_qt5agg",
    "fpdf",
    "PIL",
    "PIL.Image",
    "requests",
    "gspread",
    "sqlite3",
    "json",
    "csv",
]

a = Analysis(
    [os.path.join(ROOT, "main.py")],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[os.path.join(ROOT, "hooks")],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tests",
        "pytest",
        "_pytest",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── Standalone Executable (.exe) ─────────────────────────────────────
exe_standalone = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="CivilQntify-Standalone",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # windowed mode (no console window)
    icon=ICON,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

# ── Directory Bundle (for Linux .deb/.rpm packaging) ────────────────
exe_dir = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="CivilQntify",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=ICON,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe_dir,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="CivilQntify",
)
